export enum TemplateEnum {
  FLOWCHART = "FLOWCHART",
  MINDMAP = "MINDMAP",
  TIMELINE = "TIMELINE",
  USERJOURNEY = "USERJOURNEY",
  CLASS = "CLASS",
  ENTITYRELATIONSHIP = "ENTITYRELATIONSHIP",
  SEQUENCE = "SEQUENCE",
  STATE = "STATE",
}
